---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title: Bill Ryan
keywords: billryan
description: Home of Rhett
source_link: http://www.yuanbin.me
favicon:
touch_icon:
google_analytics_key: UA-32317667-5
disqus_shortname: homepage-billryan


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  gray: '#e3e3e3'
  sepia-bg: '#704214'
  sepia-ft: '#f3eacb'
  midnight-blue: '#012345'
  yellow: '#FFFF00'
